РК 1
frontend-park-mail-ru/2023_1_Technokaif pull request #2
Opened 2023-03-01 21:03 UTC by GodofRussia

2023-03-01 21:56 UTC, grishbar requested changes

2023-03-01 21:56 UTC, grishbar commented on .eslintignore
> +/server
почему сервер в игноре? его тоже надо линтить

2023-03-01 21:56 UTC, grishbar commented on .eslintrc
> +    },
пока что норм не забыть добавить крутой какой-нибудь конфиг, например [airbnb](https://www.npmjs.com/package/eslint-config-airbnb) или [гугловский](https://github.com/google/eslint-config-google)

2023-03-01 21:56 UTC, grishbar commented on .vscode/settings.json
> +}
что это такое?) оно точно нужно? 
Также можете сделать общие настройки для ide, например указать какие плагины вы рекомендуете для проекта, например (gitlens, brackets colorize) еще какие нибудь которые используете

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/checkAuth.js
> +}
это утилитарная функция, должна быть в папке utils, можно создать директорию тут, можно вынести в глобальную директорию utils

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/loginAjaxReq.js
> +}
все запросы в современном мире делаются при помощи [fetch](https://learn.javascript.ru/fetch),
также проверять на успешность запроса нужно при помощие [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/registerAjaxReq.js
> +}
тут тоже, надо переделать на fetch, + надо уметь обрабатывать ошибки в запросах, вам очень легко может прийти некорректный json, так что нужно будет добавить try catch, и в идеале обрабтывать в верстке ошибки, хотя бы [alert](https://learn.javascript.ru/alert-prompt-confirm) делать

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/validation.js
> +'use strict';
эти все функции в утилиты, перенести и на них бы тесты написать

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/validation.js
> +
не забыть всем функция добавить jsdoc

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/validation.js
> +    let flag = false;
переменных типа flag object thing и тому подобное в коде быть не должно, каждая переменная должна четко, показывать, что в ней хранится

2023-03-01 21:56 UTC, grishbar commented on public/api/auth/validation.js
> +    const reg = /^[a-z0-9_]{4,20}$/;
использование регулярок не приветствуется, потому, что это невозможно читать, так, что если будет куча свободного времени, то лучше от них избавиться, но не обязательно.
Также тут нужно вынести `const reg = /^[a-z0-9_]{4,20}$/;` из функций так как на каждый вызов функции создается новая регулярка, а это довольно ресурсоемкая операция

2023-03-01 21:56 UTC, grishbar commented on public/components/Menu/Menu.js
> +    #name;
а что такое # ? расскажите для чего с ним переменные создаете

2023-03-01 21:56 UTC, grishbar commented on public/components/Menu/Menu.js
> +        }).forEach((e) => this.#parent.appendChild(e));
очень сложная функция получилась, давайте разобьем ее на мелки функции

2023-03-01 21:56 UTC, grishbar commented on public/components/Navbar/Navbar.js
> +class Navbar {
не забыть дописать у классов jsdoc

2023-03-01 21:56 UTC, grishbar commented on public/index.html
> +</body>
кажется нужно объединить все скрипты в один, чтобы не подключать их по очереди, также подумать про асинхронную подгрузку скриптов, нужна ли она тут
https://learn.javascript.ru/script-async-defer

2023-03-01 21:56 UTC, grishbar commented on public/index.js
> +        }
вот здесь должен бэк говорить вам что делать, и у вас должна быть утилитарная функция которая в зависимотси от кодов ответа бэка что-то делает

2023-03-01 21:56 UTC, grishbar commented on public/modules/ajax.js
> +    const noop = () => {};
вынести в глобальные константы

2023-03-01 21:56 UTC, grishbar commented on server/index.js
> +    }
подумать про интернационализацию, возможно хранить языки в каком нибудь .json файле и хотя бы в ру и в английском варианте например можно воспользоваться https://www.npmjs.com/package/i18n

2023-03-01 21:56 UTC, grishbar commented on public/static/css/style.css
> +    font-weight: 700;
самые стандартные стили типо font-size 40px, какие-то отступы постоянно повторяющиеся все цвета надо вынести в css константы и их использовать везде, чтобы не было вероятности ошибки человеческого фактора и кто-то бы сделал отступы не стандартизированные

2023-03-01 21:56 UTC, grishbar commented on public/static/css/style.css
> +}
методология бэм запрешает комбинаторы, поэтому лучше ими не пользоваться а просто накидывать везде классы, так будет куда масштабирауеме и будет проще рефакторить

2023-03-01 21:56 UTC, grishbar commented on public/static/css/style.css
> +}
нужно сделать глобавльный css файл где сбросите все ненужные вам браузерные стили

2023-03-02 08:29 UTC, KolobokMysnoy commented on public/api/auth/validation.js
> +'use strict';
Убрал

2023-03-02 18:08 UTC, KolobokMysnoy commented on .eslintignore
> +/server
Убрал

2023-03-02 18:10 UTC, KolobokMysnoy commented on public/api/auth/checkAuth.js
> +}
Перенесена

2023-03-05 19:31 UTC, KolobokMysnoy commented on public/api/auth/validation.js
> +
Сделано

2023-03-05 19:31 UTC, KolobokMysnoy commented on public/api/auth/validation.js
> +    let flag = false;
Убрано

2023-03-05 19:31 UTC, KolobokMysnoy commented on public/api/auth/validation.js
> +    const reg = /^[a-z0-9_]{4,20}$/;
Потом

2023-03-05 19:32 UTC, KolobokMysnoy commented on .eslintrc
> +    },
Потом добавим

2023-03-06 12:52 UTC, closed without merging