Album, favorite and playlist
frontend-park-mail-ru/2023_1_Technokaif pull request #24
Opened 2023-04-30 01:23 UTC by GodofRussia

2023-05-02 20:36 UTC, grishbar requested changes

2023-05-02 20:36 UTC, grishbar commented on package.json
> +    "jade": "^0.29.0",
почему понадобился даунгрейд?

2023-05-02 20:36 UTC, grishbar commented on public/router/Router.ts
> +    }
пермишоны надо будет переписать, у них должны быть уникальные idшники, так как сейчас пытаешься сравнить по ссылке объект, чтобы посмотреть была заргестрирована очередное ограничение или нет, что очень не безопасно. Кажется будет неплохо завести объект ограничения где-нибудь и тут их использовать, и также в бдущем можно будет завести новые пермишоны и без проблем добавить

2023-05-02 20:36 UTC, grishbar commented on public/router/Router.ts
> +    }
отказываемся от хранения объектов в window, храним в локалсторадж данные о последнем треке

2023-05-02 20:36 UTC, grishbar commented on public/router/Router.ts
> +    #isRegExp(path):null|PathConfig {
isDynamicPath

2023-05-02 20:36 UTC, grishbar commented on public/router/Router.ts
> +    }
registerDynamicRoute

2023-05-02 20:36 UTC, grishbar commented on public/router/Router.ts
> +        const isStart = sessionStorage.getItem('isStart') === 'true';
отказаться от isrefresh и isstart

2023-05-02 20:36 UTC, grishbar commented on public/router/Router.ts
> +            this.#previousParams = JSON.parse(previousParamsFromStore);
обернуть try catch

2023-05-02 20:36 UTC, grishbar commented on public/router/popPath.ts
> +export function popAuthUser(path:string, direction:string):string {
direction должна быть enum или объектом as const

2023-05-02 20:36 UTC, grishbar commented on public/views/libraryPlaylistsView.ts
> +                break;
для чего тут switch а не if?

2023-05-02 20:36 UTC, grishbar commented on public/api/albums/getAlbumById.js
> +};
где-то вы назваается функция с # а тут c _ нужно идентично везде одинаково называть

2023-05-02 20:36 UTC, grishbar commented on public/api/albums/getAlbumById.js
> +const __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
обсудили, что это надо убрать

2023-05-02 20:36 UTC, grishbar commented on public/api/albums/likeDislike.js
> +const __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
убрать

2023-05-02 20:36 UTC, grishbar commented on public/api/playlists/addTrackAjaxRequest.ts
> +        status = 'OK';
в status нцжно класть константу

2023-05-07 21:30 UTC, grishbar requested changes

2023-05-07 21:30 UTC, grishbar commented on public/actions/Actions/ActionsSearch.ts
> +    gotPlaylists(playlists:PlaylistApi) {
почему тут везде got а не get

2023-05-07 21:30 UTC, grishbar commented on public/api/ApiAnswers.ts
> +type sexType = 'M'|'F'|'O';
as const

2023-05-07 21:30 UTC, grishbar commented on public/api/artists/likeDislike.ts
> +    });
а мы тут не можем подвзяться на код ответа? бэк должен отдавать 200 если все ок и другие коды в иных случаях

2023-05-07 21:30 UTC, grishbar commented on public/api/artists/likeDislike.ts
> +    });
и тут также

2023-05-07 21:30 UTC, grishbar commented on public/components/BaseComponent.js
> +                        || nameComp === componentsNames.ALBUM || componentsNames.ARTIST_CONTENT) {
[componentsNames.FEED_CONTENT, componentsNames.SEARCH_CONTENT].includes(nameComp);

2023-05-07 21:30 UTC, grishbar commented on public/components/BaseComponent.js
> +                        component = list.filter((comp) => comp.name === componentsNames.MAIN);
list.find

2023-05-07 21:30 UTC, grishbar commented on public/components/BaseComponent.js
> +                                return;
когда умышленно завершаешь исполнение кода будет лучше если будешь возвращать null, так как функция по дефолту возвращает undefined и если null то будет понятно, что это где-то осознанно вылетело а если где-то undefined, то будет понятно что значит функция ничего не вернула

2023-05-07 21:30 UTC, grishbar commented on public/components/ComponentsRenders.ts
> +        main.id = 'cont';
должно быть взято из констант

2023-05-07 21:30 UTC, grishbar commented on public/components/ComponentsRenders.ts
> +            Router.go('/login');
тут также должно быть в кностантах, также не забыть в будуще типизировать функцию Router.go, чтобы она принимала, только определенные константы старниц

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Album/album.js
> +                    }
PlayerActions.changePlayState(!SongStore.isPlaying);

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Album/album.js
> +                }
тернарный оператор

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Album/album.js
> +                }
```
let artistsText = state.artists.reduce((acc, { name }) => {
    acc.push(name)
    return acc;
}, []).join(' ');
```

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Album/album.js
> +    }
лучше не писать вложенные if else это очень сложно читается:
```
if (this.firstPlay && newState) {
      this.firstPlay = true;
      this.playButton.src = imgPath.pauseAlbum;
}

if (this.firstPlay && !newState) {
      this.isPlaying = false;
      this.playButton.src = imgPath.playAlbum;
}
```

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Album/album.js
> +        });
этот промис сразу зарезолвится если метод appendElement асинхронный, нужно `super.appendElement().then` использовать если же метож синхронный то смысла в промисе нет

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.js
> +            ).length > 0),
reduce

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.js
> +        ).length;
reduce

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.js
> +                        if (SongStore.exist && SongStore.trackInfo.artists.filter((element) => element.name === ContentStore.state[pageNames.ARTIST_PAGE].artist.name).length > 0) {
вынети действия с массивом из условия, так как слишком длинная строчка получается, также тут нужен метод массива find а не filter

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.js
>                      break;
```
imgLike.src = artist.isLiked ? imgPath.liked : imgPath.notLiked;
```

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Library/libraryPlaylists.ts
> +        if (name === 'Your playlists') {
из констант нужно взять

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.less
> +}
можна грид не нада 🙏🙏🙏

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +            search.addEventListener(METHOD.CHANGE_FIELD_IMMEDIATELY, funcOnSearch);
тут надо заиспользовать throttle или debounce, чтобы не делать черзчур много запрсов на поиска на бэкенд

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +        Array.from(trackLines).reduce((previousValue, currentValue, index, array) => {
функции reduce, filter, find должны выполнять задачу для которой созданы, потому что так намного проще читается, другой разработчик когда видит reduce, сразу ждет, что тут какой-то результирующий массив будет на основе trackLines, но это не так, поэтому тут лучше просто for пройтись

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +            const currentIndex: HTMLDivElement = currentValue.querySelector(`.${this._config.lineIndex}`) as HTMLDivElement;
каждый элемент селектишь дважды вначале как currentIndex, на следующей итерации как prevIndex, положи предыдущее значение в замыкание

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +                currentIndex.innerText = String(currentId - 1);
не очень понимаю, что происходит в этом блоке кода, можешь пояснить пожалуйста

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +        const indexBlock: NodeListOf<HTMLDivElement> = document.querySelectorAll(`.${this._config.lineIndex}`);
элементы которые хранят массивы должны либо иметь множественное значение либо заканчиваться на Array, Arr, List и тому подобное

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +        dropDown.options.style.gap = '5px';
вот таке решение будет куда болле масштабируемым
```
dropDown.options.style = {
...dropDown.options.style,
padding: '5px',
gap: '5px',
}
```

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +                    && event.target !== another) {
сравниваешь объекты, так делать не надо, очень легко ошибиться, добавь им id или какой-нибудь атрибут, где не надо выполнять это событие и проверяй просто:
```
if (event.target.getAttribute("dont-click")) {
    return null;
}
```

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +
должна быть отдельнай утилитарная функция проверки аутентификации и редиректа, если захотите всех в другое место редиректить, везде вручную исправлять?

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Navbar/Navbar.ts
> +                    });
тут все действия синхронные промис излишен

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Navbar/burgerMenu.ts
> +}
арггрх что за пустой код убратьб!

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Playlist/library.less
> +  }
перекрытие стилей должно быть только в одном файле, в одном месте, не надо дублировать

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Playlist/library.less
> +  transition: all 0.3s ease;
старайся по возможности избегать transition all так как это довольно напряжно для браузера, будет лучше если будешь указывать только нужные css свойства

2023-05-07 21:30 UTC, grishbar commented on public/components/bigComponents/Playlist/library.less
> +  transition: all 0.3s ease;
также для всех анимаций можно указывать свойство [will-change](https://frontender.info/css-will-change-property/) оно также поможет оптимизировать работу рендеринга в браузере

2023-05-11 20:14 UTC, KolobokMysnoy commented on public/actions/Actions/ActionsSearch.ts
> +    gotPlaylists(playlists:PlaylistApi) {
Так как мы уже нашли Playlist, поэтому использовали got

2023-05-11 20:31 UTC, KolobokMysnoy commented on public/components/bigComponents/Album/album.js
> +                    }
Поправил

2023-05-11 20:31 UTC, KolobokMysnoy commented on public/components/bigComponents/Album/album.js
> +                }
Поправил

2023-05-11 20:34 UTC, KolobokMysnoy commented on public/components/bigComponents/Album/album.js
> +                }
Поправил

2023-05-11 20:36 UTC, KolobokMysnoy commented on public/components/bigComponents/Album/album.js
> +    }
Поправил, буду учитывать

2023-05-11 20:58 UTC, KolobokMysnoy commented on public/components/bigComponents/ArtistContent/artistContent.js
> +            ).length > 0),
![image](https://github.com/frontend-park-mail-ru/2023_1_Technokaif/assets/71096930/5a14c1ce-9596-4447-bd16-a9fb6fff40f2)

2023-05-11 20:59 UTC, KolobokMysnoy commented on public/components/bigComponents/ArtistContent/artistContent.js
> +        ).length;
Выше исправления

2023-05-11 21:06 UTC, KolobokMysnoy commented on public/components/bigComponents/ArtistContent/artistContent.js
> +                        if (SongStore.exist && SongStore.trackInfo.artists.filter((element) => element.name === ContentStore.state[pageNames.ARTIST_PAGE].artist.name).length > 0) {
![image](https://github.com/frontend-park-mail-ru/2023_1_Technokaif/assets/71096930/eb51422a-d0ed-4164-b0cd-b4cb21530e07)

2023-05-11 21:07 UTC, KolobokMysnoy commented on public/components/bigComponents/ArtistContent/artistContent.js
>                      break;
Исправил

2023-05-11 21:14 UTC, KolobokMysnoy commented on public/components/bigComponents/LineList/lineList.ts
> +        dropDown.options.style.gap = '5px';
Исправил

2023-05-11 21:29 UTC, KolobokMysnoy commented on public/components/BaseComponent.js
> +                        component = list.filter((comp) => comp.name === componentsNames.MAIN);
Исправил

2023-05-12 16:54 UTC, GodofRussia commented on public/api/ApiAnswers.ts
> +type sexType = 'M'|'F'|'O';
поменял везде на enum

2023-05-12 16:56 UTC, GodofRussia commented on public/api/artists/likeDislike.ts
> +    });
я подвязал на коды внтури Ajax класса, но так как кодов немного с бека, то просто передаю в случае не респонс ок что всё успешно. Могу сделать обработчики с разными ошибками нав

2023-05-12 16:59 UTC, GodofRussia commented on public/components/BaseComponent.js
> +                        || nameComp === componentsNames.ALBUM || componentsNames.ARTIST_CONTENT) {
поправил

2023-05-12 17:39 UTC, GodofRussia commented on public/components/BaseComponent.js
> +                                return;
у нас прописано, где нужно не void, а в основном функции процедурные и нельзя пихать null

2023-05-12 17:40 UTC, GodofRussia commented on public/components/BaseComponent.js
> +                                return;
изменил часть ретернов

2023-05-12 17:45 UTC, GodofRussia commented on public/components/ComponentsRenders.ts
> +        main.id = 'cont';
реди

2023-05-12 19:06 UTC, GodofRussia commented on public/components/ComponentsRenders.ts
> +            Router.go('/login');
поменял

2023-05-12 19:24 UTC, KolobokMysnoy commented on public/components/bigComponents/LineList/lineList.ts
> +            search.addEventListener(METHOD.CHANGE_FIELD_IMMEDIATELY, funcOnSearch);
Удалено

2023-05-12 19:38 UTC, GodofRussia commented on public/components/bigComponents/Album/album.js
> +        });
сменили на логику без промисов

2023-05-12 19:40 UTC, GodofRussia commented on public/components/bigComponents/LineList/lineList.less
> +}
нада, как утешение - на мобиле их меньше!!!

2023-05-12 22:13 UTC, GodofRussia commented on public/components/bigComponents/Navbar/Navbar.ts
> +                    });
поправил

2023-05-12 22:13 UTC, GodofRussia commented on public/components/bigComponents/Navbar/burgerMenu.ts
> +}
готово

2023-05-12 22:31 UTC, GodofRussia commented on public/components/bigComponents/Library/libraryPlaylists.ts
> +        if (name === 'Your playlists') {
поправил

2023-05-12 22:39 UTC, GodofRussia commented on public/components/bigComponents/Playlist/library.less
> +  }
не очень понятно, тут не перекрывается, это просто внутренний селектор на a:hover

2023-05-12 22:44 UTC, GodofRussia commented on public/components/bigComponents/Playlist/library.less
> +  transition: all 0.3s ease;
поставил

2023-05-12 22:55 UTC, GodofRussia commented on public/components/bigComponents/LineList/lineList.ts
> +        const indexBlock: NodeListOf<HTMLDivElement> = document.querySelectorAll(`.${this._config.lineIndex}`);
сменил имя

2023-05-12 22:56 UTC, KolobokMysnoy commented on public/components/bigComponents/LineList/lineList.less
> +}
Это мнение конкретного человека, и оно может отличаться от мнения нашей команды.

2023-05-15 17:05 UTC, grishbar requested changes

2023-05-15 17:05 UTC, grishbar commented on .github/workflows/actions.yml
> +          node-version: 16
это поставит последнюю 16 ноду? Не лучше ли будет если мы зафиксируем тут прям конкретную версию?

2023-05-15 17:05 UTC, grishbar commented on .gitignore
> +tmp.js
что это за файлик такой?)

2023-05-15 17:05 UTC, grishbar commented on public/api/ApiAnswers.ts
Надо сгенерировать типы при помощи открытых библиотек или написать свою кастомную (это не сильно сложно) например есть библиотека - https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-typescript
то есть вы скачиваете курлом файл - https://fluire.ru/swagger/doc.json и потом этот файл скармливаете в библиотеку, соответственно в package.json должен быть скрипт который всем этим занимается

2023-05-15 17:05 UTC, grishbar commented on public/api/artists/likeDislike.ts
> +    });
ладно, так норм оставляй

2023-05-15 17:05 UTC, grishbar commented on public/components/BaseComponent.ts
> +                    if ([componentsNames.FEED_CONTENT, componentsNames.SEARCH_CONTENT, nameComp === componentsNames.ALBUM, componentsNames.ARTIST_CONTENT].includes(nameComp)) {
кажется тут ошибка:
```nameComp === componentsNames.ALBUM```

2023-05-15 17:05 UTC, grishbar commented on public/components/BaseComponent.ts
> +                        component = list.find((comp) => comp.name === componentsNames.MAIN);
будет лучше если в другую переменную тут положишь, а то ты зашел в if сначала найдя один компонент а потом внутри if его переопределил и он может не найтись, то есть строчки
81 и 94 хотя они вложенные выглядят супер странно

2023-05-15 17:05 UTC, grishbar commented on public/components/ComponentsRenders.ts
> +    }
почему бы во всех этих методах не написать вот так:
```
new ArtistContent(parent, setupArtistContent()).render();
```
кажется, что много лишних строк которые не добавляют читаемости и используют немного лишней памяти на выполнение функции, хоть это и супер незначительно но можем избавиться

2023-05-15 17:05 UTC, grishbar commented on public/components/bigComponents/Album/album.ts
> +                const buttons = document.querySelector('.js__button__play');
почему `buttons`, там же будет всего один элемент так как ты  `querySelector`  используешь

2023-05-15 17:05 UTC, grishbar commented on public/components/bigComponents/Album/album.ts
> +                    resolve('');
у тебя тут все действия синхронно вызываются, даже если хотя бы одно из этих действия было бы асинхронным, все равно промис бы зарезолвился раньше, чем выполнится твое асинхронное действие, так как ты все инструкции тут вызываешь синхронно,  надо убрать излишний промис

2023-05-15 17:05 UTC, grishbar commented on public/components/bigComponents/Album/ifEquals.js
> +}
дублируешь эту фкнцию в двух местах надо вынести в утилиты, дать более понятное описание, сейчас не очень понятно, что она там делает с шаблонами и зачем она нужно

2023-05-15 17:05 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.ts
> +            return acc;
```
return acc +  track.artists.find((trackArtist) => trackArtist.name === artist.name) ?? 0
```

2023-05-15 20:31 UTC, GodofRussia commented on public/components/BaseComponent.ts
> +                    if ([componentsNames.FEED_CONTENT, componentsNames.SEARCH_CONTENT, nameComp === componentsNames.ALBUM, componentsNames.ARTIST_CONTENT].includes(nameComp)) {
поправил

2023-05-15 20:37 UTC, GodofRussia commented on public/components/ComponentsRenders.ts
> +    }
сделано

2023-05-15 20:39 UTC, GodofRussia commented on public/components/bigComponents/Album/album.ts
> +                const buttons = document.querySelector('.js__button__play');
паменял

2023-05-15 20:46 UTC, GodofRussia commented on public/components/bigComponents/Album/album.ts
> +                    resolve('');
изменил

2023-05-15 21:25 UTC, KolobokMysnoy commented on public/api/ApiAnswers.ts
Сделано, файл schema.ts

2023-05-15 21:30 UTC, GodofRussia commented on public/components/bigComponents/ArtistContent/artistContent.ts
> +            return acc;
сделяль через тернарный

2023-05-15 21:36 UTC, GodofRussia commented on .github/workflows/actions.yml
> +          node-version: 16
поставил ласт стейбл версию

2023-05-15 21:37 UTC, GodofRussia commented on .gitignore
> +tmp.js
убрал

2023-05-15 22:17 UTC, GodofRussia commented on public/components/BaseComponent.ts
> +                        component = list.find((comp) => comp.name === componentsNames.MAIN);
сделяль

2023-05-15 22:45 UTC, GodofRussia commented on public/components/bigComponents/Playlist/library.less
> +  transition: all 0.3s ease;
убрал

2023-05-15 22:47 UTC, KolobokMysnoy commented on public/components/bigComponents/Album/ifEquals.js
> +}
В одной папке

2023-05-15 22:56 UTC, GodofRussia commented on public/components/bigComponents/LineList/lineList.ts
> +                currentIndex.innerText = String(currentId - 1);
это проход по трекам и восстановление порядка индексации

2023-05-15 23:41 UTC, GodofRussia commented on public/components/bigComponents/LineList/lineList.ts
> +        Array.from(trackLines).reduce((previousValue, currentValue, index, array) => {
сделал адекватную функу

2023-05-15 23:41 UTC, GodofRussia commented on public/components/bigComponents/LineList/lineList.ts
> +            const currentIndex: HTMLDivElement = currentValue.querySelector(`.${this._config.lineIndex}`) as HTMLDivElement;
сделал норм см выше комм

2023-05-17 22:27 UTC, grishbar approved these changes

2023-05-17 22:27 UTC, grishbar commented on .github/workflows/actions.yml
> +
по правильному деплоя не должно быть на push, так как деплой очень опасная операция и должна происходить контролируемо, то-есть должен быть деплой инженер, который вручную запускает деплой и смотрит, что никакие метрики проекта не страдают, что не произошло нигде регресса по функционалу и тому подобное, поэтому деплой лучше в CI не класть или ставить деплой на мердж в определенную ветку. Сейчас можно так оставить
Также можно создать таску, что на каждый деплой меняется версия приложения в package.json, чтобы можно было откатывать на нужные версии, смотреть какакая версия приложения сейчас и тому подобное

2023-05-17 22:27 UTC, grishbar commented on .gitignore
> +data.yaml
а что в этом файле хранится? для чего он в игноре?

2023-05-17 22:27 UTC, grishbar commented on public/static/css/reset.less
> +//    /* display: inline-block; */
нужно либо расскоментить все, либо удалить, я за то, чтобы расскоментить

2023-05-17 22:27 UTC, grishbar commented on public/router/Router.ts
> +            this.#previousParams = JSON.parse(previousParamsFromStore);
тут так и не обернули try catch

2023-05-17 22:27 UTC, grishbar commented on public/router/Router.ts
остались неисправленные комменты в роутере, и все еще нужно переписать его значительно, сделать намного проще. Вынести и сделать более масштабируемыми пермишоны, избавитьcя от хранения данных в window и еще поискать моменты для улучшения
можно не исправлять сейчас, можно завести задачу как тех долг

2023-05-17 22:27 UTC, grishbar commented on public/modules/Ajax.ts
> +        if (url !== apiUrl.AUTH && url !== apiUrl.LOGIN && url !== apiUrl.ALBUM_SEARCH_API && url !== apiUrl.ARTIST_SEARCH_API && url !== apiUrl.TRACK_SEARCH_API) {
```
![apiUrl.AUTH, apiUrl.LOGIN  ....].includes(url)
```

2023-05-17 22:27 UTC, grishbar commented on public/modules/Ajax.ts
> +                }
по правильному если нет csrf токена, то нужно попытаться перезапросить его и повторно выполнить запрос и ограничить количество повторных попыток например тремя
можно сейчас не исправлять, завести задачу как техдолг

2023-05-17 22:27 UTC, grishbar commented on public/modules/Ajax.ts
> +class Ajax {
так как у вас все запросы должны проходить исключительно через этот класс, то правильно бы было создать линтовое правило, которое запрещает использовать fetch во всех частях проекта кроме этого файла, можно также как техдолг записать

2023-05-17 22:27 UTC, grishbar commented on public/modules/Ajax.ts
> +};
as const

2023-05-17 22:27 UTC, grishbar commented on public/modules/Ajax.ts
> +const noop = (data: unknown = true) => data;
это не noop функция она возвращает аргументы который получила, причем только, что странно, либо переименовать функцию, либо перестать тут что либо возвращать, также если хотите можно вобще от нее избавиться и использовать conditional chaining и внутри вашего класса вызывать функциию которые потенциально undefined как `fn?.()`

2023-05-17 22:27 UTC, grishbar commented on public/modules/Ajax.ts
> +            return csrfAjax().then((csrf) => {
при каждом post и delete запросе вы перезапрашиваете csrf токен, это ненужная нагрузка на сервер, то есть при каждом не гет запросе вместо одного вы делаете два и увеличиваете время выолнения вашего запроса на фронте в разы, csrf токен надо получить один раз при старте приложения, и дальше пользоваться им и обновлять только если старый протух

2023-05-17 22:27 UTC, grishbar commented on public/api/auth/csrfAjaxReq.ts
> +            const dataObj = data as csrfResponse;
в идеале таких кастов быть не должно, так как каждый такой каст значит, что где-то что-то не так типизировано, и если сюда придет объект не того типа который захардкожен, то все отработает неправильно, нужно сделать, чтобы ваш `Ajax.get` метод либо принимал дженерики, либо, что еще лучше исходя из url куда запрос сам понимал какие типы у ответа должны быть и не давал вбить url которые не описан в схеме

2023-05-17 22:33 UTC, KolobokMysnoy commented on .gitignore
> +data.yaml
data.yaml это файл, который создаётся во время скачивания сваггера, и просто игнорится, а не удаляется. Можно убрать из гитигнора и добавить в удаление, после выполнения команд, если нужно

2023-05-17 23:13 UTC, merged