Dev/rk4
frontend-park-mail-ru/2023_1_Technokaif pull request #27
Opened 2023-05-20 23:28 UTC by KolobokMysnoy

2023-05-22 05:38 UTC, grishbar requested changes

2023-05-22 05:38 UTC, grishbar commented on grep
надо бы удалить этот файлик, зачем он нужен?

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.handlebars
> +            <img class="shareButton" src="/static/svg/share.svg">
а там у нас завезли же на бэкенде сервер для статики на s3 там мы картинки не храним?
Если храним, то лучше оттуда брать иконки и все такое

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/FeedContent/feedContent.less
> +        padding-left: 2.5%;
лучше не использовать относительные величины на одном каком-то уникальном элементе, они должны быть либо на всем проекте, либо нигде. Так как становится очень сложно поддерживать такое, ты привык везде к одному поведению, а тут бац и у тебя элемент который действует на странице иначе чем другие, очень легко становится посадить баг

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/Library/favorite.less
> +    padding-right: 2.5%;
тут тоже самое

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +        // @ts-ignore
для чего тут ts-ignore?
в идеале в проекте их быть не должно, по крайней мере плодить новые точно не стоит.
так как лишаетесь всех преимуществ тайпскрипта, в итоге если здесь будет какая-то ошибка с типами, то узнаете только в продакшене, а не на этапе компиляции

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/Navbar/navbar.less
> +        width: calc(100% - 300px);
я все еще за то, чтобы подумать и сделать так, чтобы не пришлось использовать calc, так как каждый calc на странице чреват каким-нибудь неожиданным багом, и очень сложно поддерживать это, никто не будет искать calc в других элементах, когда будет менять размеры какого-либо элемента.
по крайней мере вот эти 300px надо вынести в константу и элементу чьи размеры равны этим 300px туда эту константу положить

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/form/form.less
> +    height: 1.4rem;
так вроде же решили отказаться от rem нет?

2023-05-22 05:38 UTC, grishbar commented on public/components/bigComponents/player/player.ts
> +        }
кажется проще удалить все классы и поставить вот этот один класс

2023-05-22 05:38 UTC, grishbar commented on public/components/smallComponents/ModalWindow/modalWindow.less
> +  background-color: rgba(0, 0, 0, 0.5);
прям в это же файле в двух местах используется этот цвет, должен быть в константе

2023-05-22 05:38 UTC, grishbar commented on public/components/smallComponents/ModalWindow/modalWindow.less
> +  background: hsla(0,0%,100%,.1);
за что hsla?((( мне плоха
также не забыть в других местах убрать

2023-05-22 05:38 UTC, grishbar commented on public/components/smallComponents/input/input.less
> +    margin-bottom: calc(calc(1 / 3) * 1rem);
может просто в px зададим, это же невозможно прочитать и поправить хоть как-либо

2023-05-22 05:38 UTC, grishbar commented on public/static/css/constants.less
> +@tinyTextFont: 0.6rem;
почему они `not relative` если они в rem давайте, тогда в px их зададим

2023-05-22 16:19 UTC, GodofRussia commented on public/components/bigComponents/ArtistContent/artistContent.handlebars
> +            <img class="shareButton" src="/static/svg/share.svg">
это относительный путь, nginx сам на s3 хранилище идёт так

2023-05-22 16:23 UTC, GodofRussia commented on grep
убрал

2023-06-02 04:16 UTC, GodofRussia commented on public/components/bigComponents/form/form.less
> +    height: 1.4rem;
ремами задаются сейчас блоки, чтоб под адаптив выглядело не убого. Судя по виду получается.

2023-06-02 04:37 UTC, GodofRussia commented on public/components/bigComponents/player/player.ts
> +        }
поправил

2023-06-02 04:37 UTC, GodofRussia commented on public/components/bigComponents/player/player.ts
> +        }
давно уже, забыл там отписать

2023-06-02 04:39 UTC, GodofRussia commented on public/components/smallComponents/ModalWindow/modalWindow.less
> +  background: hsla(0,0%,100%,.1);
убрал

2023-06-02 04:40 UTC, GodofRussia commented on public/static/css/constants.less
> +@tinyTextFont: 0.6rem;
ошиблись с коммом, там уже давно просто fonts....

2023-06-02 04:42 UTC, GodofRussia commented on public/components/smallComponents/ModalWindow/modalWindow.less
> +  background-color: rgba(0, 0, 0, 0.5);
сделяль

2023-06-02 04:45 UTC, GodofRussia commented on public/components/bigComponents/LineList/lineList.ts
> +        // @ts-ignore
в данном случае там точно нужные данные будут - у нас много ts-ignore потому, что он на массиве элемент по индексу с любыми проверками бракует, у нас именно там осталось

2023-06-02 04:47 UTC, GodofRussia commented on public/components/bigComponents/FeedContent/feedContent.less
> +        padding-left: 2.5%;
это общий класс для паддингов. Как я понял, Игнат юзал ремы для внутренних блоков и текста и иногда проценты, чтобы задать скейл при стягивании/растягивании экрана (типа всё ради адаптива, так бы мы px оставили)

2023-06-02 18:31 UTC, grishbar approved these changes

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/ArtistContent/artistContent.ts
> +                nothingPlacement?.appendChild(textOfNothing);
на самом деле, делать много, optional chaining не очень правильно по сути тут надо выкидывать ошибку и обрабатывать каким-нибудь глобальным хэндлером, который вместо этого блока покажет блок с ошибкой

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/FeedContent/feedContent.ts
> +                    if (key === 'Tracks') {
почему не из констант взято а захардкожено?(

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/Library/favorite.handlebars
> +<!--    <div class="js__divider__placement"></div>-->
э! такого быть не должно

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/Library/libraryPlaylists.ts
> +                // @ts-ignore
почему тут игнор кажется его быть не должно тут, нужно поправить, иначе словите очень неожиданную багу

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/Library/libraryPlaylists.ts
> +                }
нужно прервать цикл когда нашли подобный элемент вам же не последний подобный элемент нужен, если нужен последний то пройти с конца цикла и также прервать.

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/Library/libraryPlaylists.ts
> +                nothingPlacement.appendChild(textOfNothing);
вот это должна быть глобальная утилитарная функция, чтобы не писать каждый раз

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/Library/libraryPlaylists.ts
> +        // elementForDivider?.classList.add('divider');
смэрт

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +        }, 500);
это надо сделать через css, там указаывать через какое время начинать изменять анимацию, а в js нужно просто класс добавить стилевой

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> -        //
убрали заккоменченный код уважаемо

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +                        'Song is added to playlist!',
это в константах должно быть

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/LineList/lineList.ts
> +            anothers.forEach((anotherElement, index) => {
forEach опасный метод как мы выяснили, лучше for использовать

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/player/player.ts
> +                const artistId: string|undefined = spanElement.dataset?.id;
тут указывать тип излишне, так как он автоматически опредилится, это лучше

2023-06-02 18:31 UTC, grishbar commented on public/components/bigComponents/player/player.ts
> +                // @ts-ignore
ну от игнора бы избавиться)

2023-06-02 18:32 UTC, merged