Good PR
frontend-park-mail-ru/2023_1_Technokaif pull request #5
Opened 2023-03-06 14:55 UTC by KolobokMysnoy

2023-03-06 15:11 UTC, grishbar commented
надо изменить название пра, на то, что было тут сделано

2023-03-06 15:18 UTC, grishbar requested changes

2023-03-06 15:18 UTC, grishbar commented on public/components/MainWindowRender/mainWindow.js
> +import { homeSetup } from '../../pages/home/homeSetup.js';
за это должен отвечать линтер, на забыть первым делом настроить его, (взять какой-то классный конфиг) перед там как брать следующие задачи

2023-03-06 15:18 UTC, grishbar commented on public/components/Navbar/Navbar.js
> +        // this.#parent.innerHTML += templateInnerHtml;
задокументированного кода в проекте быть не должно

2023-03-06 15:18 UTC, grishbar commented on public/components/Navbar/Navbar.js
> +        console.log(this.items);
вроде хотели избавиться от всех консоль логов, почему тут осталось?

2023-03-06 15:18 UTC, grishbar commented on public/components/TracksComp/TracksComp.js
> + */
почему тут не описаны параметры класса ?

2023-03-06 15:18 UTC, grishbar commented on public/components/sex/sex.js
>      #config;
тут также добавить jsdoc

2023-03-06 15:18 UTC, grishbar commented on public/utils/functions/validation.js
> +const forbidenEmailSymb = '<>()[],;:\\/';
это надо бы вынсти в глобальные константы, и назвать в SNAKE_CASE

2023-03-06 15:18 UTC, grishbar commented on public/utils/functions/validation.js
> +    }
для чего везде пушить и возвращать result?
можно просто `return [ERRORS.email];` и так далее

2023-03-06 15:23 UTC, KolobokMysnoy commented on public/utils/functions/validation.js
> +    }
Ну просто у нас есть проверка на confEmail выше, поэтому мы должны вернуть 2 значения в одних случаях, а в других одно. Поэтому push и вернуть.

2023-03-06 15:24 UTC, KolobokMysnoy commented on public/components/TracksComp/TracksComp.js
> + */
Ты же говорил, что это уже после 1 рк сделать, когда на TypeScript будем переписывать

2023-03-06 15:26 UTC, grishbar commented on public/components/TracksComp/TracksComp.js
> + */
Ввел в заблуждение давай свойства конструктора тоже опишем)

2023-03-06 15:26 UTC, grishbar commented on public/components/TracksComp/TracksComp.js
> + */
методы класса уже будем описывать когда появится ts

2023-03-11 12:51 UTC, grishbar requested changes

2023-03-11 12:51 UTC, grishbar commented on public/components/AlbumsComp/AlbumsComp.js
> +        // eslint-disable-next-line no-undef
го лучше задизейблим это правило в конфиге и сразу около него todo c ссылкой на задачу напишем

2023-03-11 12:51 UTC, grishbar commented on .eslintrc.js
> +        'no-restricted-syntax': 'off',
около всех правил надо оставить комментарий с ссылкой на задачу где эти правила включите

2023-03-11 12:51 UTC, grishbar commented on package.json
> +    "eslint-config-google": "^0.14.0",
надо один конфиг оставить и не должно быть зависимостей которые ты не используешь

2023-03-11 12:51 UTC, grishbar commented on .eslintignore
> +/server
почему сервер все еще сервер в игноре?

2023-03-11 12:51 UTC, grishbar commented on package.json
> +    "eslint-config-google": "^0.14.0",
нужно убрать зависимости которые не используете, и линтер должен быть только один

2023-03-11 12:51 UTC, grishbar commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
эти зависимости тоже нужно убрать

2023-03-11 12:51 UTC, grishbar commented on package.json
> +    "prettier": "2.8.4",
а преттиер вы где-то используете? не вижу его конфиг файла

2023-03-11 12:51 UTC, grishbar commented on public/api/auth/loginAjaxReq.js
> +            if (status < 300) {
что это такое?) обсуждали же что нужно на [response.ok ](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)проверять

2023-03-11 12:51 UTC, grishbar commented on public/api/auth/loginAjaxReq.js
> +            document.getElementById('serverErrors').style.display = 'block';
не нужно скрывать/показывать элемент стилями, добавляйте/убирайте элемент из dom

2023-03-11 12:51 UTC, grishbar commented on public/api/auth/registerAjaxReq.js
> +        },
тут те же проблемы что и logoutAjax

2023-03-11 12:51 UTC, grishbar commented on public/components/Menu/Menu.css
> +}
бэм запрещает комбинаторы, и тут еще очень сложные селекторы, такого быть не должно

2023-03-11 12:51 UTC, grishbar commented on public/components/Menu/Menu.css
> +.logo h1 {
тут также и пройдитесь по всем css файлам пожалуйста, если нужны стили на h1 то дайте ему класс и навесьте там стили

2023-03-11 12:51 UTC, grishbar commented on public/components/Menu/Menu.css
> +}
нужно глобально сбросить стили сбросить, у тэга a

2023-03-11 12:51 UTC, grishbar commented on public/components/Menu/Menu.js
> +    }
у функций в классе тоже должен быть jsdoc

2023-03-11 12:51 UTC, grishbar commented on public/components/Navbar/Navbar.js
>              if (e.target instanceof HTMLAnchorElement || e.target instanceof HTMLButtonElement) {
для чего этот if?
можно всегда вызывать `e?.preventDefault?.()`

2023-03-11 12:51 UTC, grishbar commented on public/components/date/date.css
> +    border: 1px rgba(255, 255, 255, .7) solid;
уже в двух местах использовал этот цвет, нужно вынести в константу

2023-03-11 12:51 UTC, grishbar commented on public/components/formFooter/formFooter.css
> +.auth-btn button, .log-reg-btn, .reg-login-btn {
одинаковые стили старайтесь вынести в какой нибудь универсалный класс, который везде будете использовать а еще лучше сделать универсальный компонент, в который можно докидывать классы и переиспользуйте ее

2023-03-11 12:51 UTC, grishbar commented on public/pages/registration/registration.js
> +}
кажется тут что-то странное происходит, почему сюда приходит несколько аргументов? типо может быть:
`getSexInString ('M', 'F',)` а что если сюда придет `getSexInString ('female')` тогда вернем M, вобщем тут что-то не так функция должна принимать один аргумент типа enum - ('male' || 'female' || 'non-binary')

2023-03-11 20:06 UTC, KolobokMysnoy commented on public/components/AlbumsComp/AlbumsComp.js
> +        // eslint-disable-next-line no-undef
Добавил global переменную, чтобы он мог находить Handlebars

2023-03-11 20:08 UTC, KolobokMysnoy commented on .eslintrc.js
> +        'no-restricted-syntax': 'off',
У нас все включения будут осуществляться из одной задачи в trello. Вставил ссылку на это задание перед всеми выключениями.

2023-03-11 20:10 UTC, KolobokMysnoy commented on package.json
> +    "eslint-config-google": "^0.14.0",
Убрал

2023-03-11 20:13 UTC, KolobokMysnoy commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
Убрал

2023-03-11 20:13 UTC, KolobokMysnoy commented on package.json
> +    "eslint-config-google": "^0.14.0",
Убрал

2023-03-11 21:50 UTC, GodofRussia commented on .eslintignore
> +/server
убрали

2023-03-11 21:53 UTC, GodofRussia commented on package.json
> +    "prettier": "2.8.4",
убрали

2023-03-12 11:34 UTC, KolobokMysnoy commented on public/pages/registration/registration.js
> +}
Исправил

2023-03-18 00:58 UTC, grishbar approved these changes

2023-03-18 00:58 UTC, grishbar commented on .eslintrc.js
> +        'no-restricted-syntax': 'off',
🔥🔥🔥

2023-03-18 00:58 UTC, grishbar commented on .eslintrc.js
> +        }],
🔥🔥🔥🔥🔥🔥

2023-03-18 00:58 UTC, grishbar commented on README.md
> +## Ссылка на деплой: http://89.208.199.114/
Ссылка на стэнд может?

2023-03-18 00:58 UTC, grishbar commented on public/api/auth/registerAjaxReq.js
> +            if (status < 300) {
😡😡😡😡😡

2023-03-18 00:58 UTC, grishbar commented on public/components/MainWindow/mainWindow.css
> +}
вынеести в какой-то глобальный файл со сборсами стилей [пример](https://medium.com/@stasonmars/%D1%81%D0%BE%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B8%CC%86-%D1%81%D0%B1%D1%80%D0%BE%D1%81-css-f5816963c82b)

2023-03-18 00:58 UTC, grishbar commented on public/components/MainWindow/mainWindow.css
> +  display: grid;
в идеале избавиться от грида

2023-03-18 00:58 UTC, grishbar commented on server/index.js
> +    const { sex } = req.body;
```const { password, email, sex... } = req.body;```

2023-03-19 22:11 UTC, merged