Kolobok mysnoy/feed/css
frontend-park-mail-ru/2023_1_Technokaif pull request #8
Opened 2023-03-16 23:06 UTC by KolobokMysnoy

2023-03-16 23:41 UTC, grishbar requested changes

2023-03-16 23:41 UTC, grishbar commented on public/components/Header/header.css
> +  font-size: 40px;
размеры шрифтов тоже бы вынести в константы, так как они должны быть на всех страницах одни и те же в идеале в районе 7 разных размеров шрифтов у вас должно быть не больше

2023-03-16 23:41 UTC, grishbar commented on public/components/Header/header.css
> +  display: none;
уже отписывал, что лучше не через css показывать элементы а вставлять и удалять их из dom

2023-03-16 23:41 UTC, grishbar commented on public/components/Header/header.less
> +  }
разве в less файлах нужны скобки фигурные?

2023-03-18 00:10 UTC, KolobokMysnoy commented on public/components/Header/header.less
> +  }
https://lesscss.org/
Все примеры с ними были, так что так и писали

2023-03-18 00:37 UTC, grishbar approved these changes

2023-03-18 00:37 UTC, grishbar commented on public/components/MainWindow/mainWindow.less
> +}
mainPageWindow

2023-03-18 00:37 UTC, grishbar commented on public/components/Menu/menu.less
> +    text-decoration: none;
у всех ссылок должны быть сбиты дэфолтные стили, чтобы не писать постоянно `text-decoration: none;` у каждой ссылки

2023-03-18 00:37 UTC, grishbar commented on public/components/Menu/menu.less
> +    letter-spacing: -0.01em;
откуда em? убратьб!!!

2023-03-18 00:37 UTC, grishbar commented on public/components/Menu/menu.less
> +    height: 0.01em;
что это такое, зачем эти стили?

2023-03-18 00:37 UTC, grishbar commented on public/components/Navbar/Navbar.css
> +  background-color: rgba(12, 12, 12, 0.8);
кажется это должно быть в константе

2023-03-18 00:37 UTC, grishbar commented on public/components/Navbar/Navbar.css
> +  width: calc(100% - 288px);
подумать есть ли возможность избавиться от calc

2023-03-18 00:37 UTC, grishbar commented on public/components/Navbar/Navbar.css
> +  text-decoration: none;
не забыть убрать когда глобально сбросите стили для всех ссылок

2023-03-18 00:37 UTC, grishbar commented on public/components/Navbar/Navbar.css
> +.navbar__logout {
кажется можно вынести в общий класс

2023-03-18 00:37 UTC, grishbar commented on public/components/TracksComp/trackComp.less
> +}
неиспользуемого кода быть не должно

2023-03-18 00:37 UTC, grishbar commented on public/components/TracksComp/trackComp.less
> +    line-height: 179.2%;
какой-то странный стиль?

2023-03-18 00:39 UTC, merged